alias c := clean

test-golden-vectors:
    #!/usr/bin/env bash
    set -euo pipefail
    cd golden-vectors
    make all
    cd ..
    ./golden-vectors/test_golden_reader

clean:
    #!/usr/bin/env bash
    set -euo pipefail
    cd golden-vectors
    make clean
    cd ..
